sudo: false
language: rust
rust: 
  - nightly

branches:
  except:
    - gh-pages

# Only while clippy is failing
matrix:
  allow_failures:
    - rust: stable
    - rust: beta
env:
  global:
    - PATH="$PATH:$TRAVIS_BUILD_DIR/target/debug"
    - RUST_BACKTRACE="1"
cache:
  directories:
    - $TRAVIS_BUILD_DIR/target
    - $HOME/.cargo

os:
  - linux
  - osx

script:
  - cargo build --verbose
  - cargo build --features "keyboard-time"
  - cargo build --features "task"
  - cargo build --features "task keyboard-time"
  - cargo build --features "idle"
  - cargo build --features "idle keyboard-time"
  - cargo build --features "idle task"
  - cargo build --features "idle task keyboard-time"
  - cargo build --features "signal"
  - cargo build --features "signal keyboard-time"
  - cargo build --features "signal task"
  - cargo build --features "signal task keyboard-time"
  - cargo build --features "signal idle"
  - cargo build --features "signal idle keyboard-time"
  - cargo build --features "signal idle task"
  - cargo build --features "signal idle task keyboard-time""
#  - cargo test -- winsz
#  - cargo test
#  - cargo test --features task -- --nocapture
