language: rust

rust:
  - nightly
os:
  - osx
  - linux
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - graphviz
matrix:
  include:
    - rust: nightly
      env: FEATURES=nightly
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/Library/Python/2.7/bin:$PATH
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update           ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz ; fi
script:
  - |
      cargo build --verbose
      cargo build --features "task"
      cargo build --features "idle"
      cargo build --features "idle task"
      travis-cargo build -- --verbose
      travis-cargo test
      travis-cargo test -- --features task
      travis-cargo bench
      travis-cargo doc -- --no-deps
after_success:
  - touch target/doc/index.html
  - travis-cargo --only nightly doc-upload 
env:
    global:
      - TRAVIS_CARGO_NIGHTLY_FEATURE="nightly"
