language: rust

rust:
  - nightly
os:
  - osx
  - linux
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - graphviz
matrix:
  include:
    - rust: nightly
      env: FEATURES=nightly
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/Library/Python/2.7/bin:$PATH
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update           ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz ; fi
script:
  - |
      cargo build --verbose
      cargo build --features "task"
      cargo build --features "idle"
      cargo build --features "idle task"
      travis-cargo build -- --verbose
      travis-cargo test
      travis-cargo test -- --features task
      travis-cargo bench
      travis-cargo doc -- --no-deps
after_success:
  - touch target/doc/index.html
  - travis-cargo --only nightly doc-upload 
env:
    global:
      - TRAVIS_CARGO_NIGHTLY_FEATURE="nightly"
      - secure="GT4YuVOwr0sigwjU119tHKXPN+GD8buwKTihJ7df4i9Gc/22PHOEYopUCef6QXMrsL2XkuOUv7Zgy1MwMJPh27ATpJxTU2uzTjmF5EuSVmLGeXn3xuVqf9UXccbqz4p7EepgmoMCDZiyPE3FMr04Bp3rw7KRon2Jrjy4hqhOMA5KXk9e/FRv9o3zBUHz33pgdkE0ofNU9818h0XOFoC1tVIjdnpTB5OIaUDAvOsZiTxn8YeVvmY6myWnoX41XCxuEhlbqweCE8zc1ys2WKnKTR1bkJCL5KoSCJaX36OK+tR7fmYpuSRnp8+rcqWSdUG3DwyLrS+LzOlAbLY9DIYFyQtmD0CWnI+dOhvmO/wxfHIOxHBWg7DNAcivwqYdFbsS2aM4nU50gzlN5yA8uG9mDWOEn+GVFBl9pbrg3pBvixQ5qbIyGktRv0FXMIkF/Y0d+5LmjRHiIxd6R1pOxkbatGGc0Idm/yvpHHjd4zfmfVH/G/NrGmPODAm1kx8412YBIR7VebyoHXxHXya463src1hlvDLJlhn0KTES/v+0MDuY2suF7jVrv7zxI7+6DYcQjy98RXJfEi6805BDoczV88y03mhsUy3gE1tjr8Wk0P1Bocc7Fasu89KgZ4HhyCoOkZhVqYhe+G1cSZkNQXkpzl/D2otkem+UA5h0stqn/wM="
