language: rust

rust:
  - nightly
os:
  - osx
  - linux
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
matrix:
  include:
    - rust: nightly
      env: FEATURES=nightly
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/Library/Python/2.7/bin:$PATH
script:
  - |
      travis-cargo --only nightly build
      travis-cargo --only nightly test
      travis-cargo --only nightly bench
after_success:
  - travis-cargo --only nightly doc-upload 
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE="nightly"
script:
  - travis-cargo --only nightly build
  - travis-cargo --only nightly test
  - travis-cargo --only nightly test -- --features winsz
  - travis-cargo --only nightly test -- --features task
