sudo: false
language: rust
rust: 
  - nightly

branches:
  except:
    - gh-pages

# Only while clippy is failing
matrix:
  allow_failures:
    - rust: stable
    - rust: beta
env:
  global:
    - PATH="$PATH:$TRAVIS_BUILD_DIR/target/debug"
    - RUST_BACKTRACE="1"
cache:
  directories:
    - $TRAVIS_BUILD_DIR/target
    - $HOME/.cargo

os:
  - linux
  - osx

script:
  - cargo build --verbose
  - cargo test -- winsz
  - cargo test
  - cargo test --features task -- --nocapture
